version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: 
      context: .
      dockerfile: dockerfile
    command: gunicorn --chdir /code poll_esports.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=*
      
    depends_on:
      - rabbitmq

  celery_worker:
    build: 
      context: .
      dockerfile: dockerfile
    command: /bin/sh -c "sleep 10 && celery -A poll_esports.celery_config worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq

  celery_beat:
    build: 
      context: .
      dockerfile: dockerfile
    command: celery -A poll_esports.celery_config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
